version: '2'
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
  postgres:
    image: postgres:9.5
    ports:
      - "5436:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/db-files/
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    tty: true
    container_name: firstleaf_test
    env_file:
      - .env.development
    links:
      - postgres
    volumes:
      - .:/app
    volumes_from:
      - box
    ports:
      - 3005:3000
    depends_on:
      - postgres
      - redis
    entrypoint: ./bin/rails-start.sh
  box:
    tty: true
    image: busybox
    volumes:
      - /box
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - web
      - postgres
      - redis
    env_file:
      - .env.development
    volumes:
      - .:/app
    entrypoint: ./bin/sidekiq-start.sh
volumes:
  postgres:
  box:
  redis:
