version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
  redis:
    image: "redis"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    depends_on:
      - db

