version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - './tmp/db:/var/lib/postgresql/data'
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3005:3005"
    depends_on:
      - db

